# Generated by Django 4.0.5 on 2022-06-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_favoritecity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritecity',
            options={'verbose_name': 'Favorite city', 'verbose_name_plural': 'Favorite cities'},
        ),
    ]
